In [ ]:
import requests
from IPython.core.display import HTML
HTML(f"""
<style>
@import "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css";
</style>
""")

# Linear Algebra using Python and Numpy
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to familiarise yourself with the concepts of linear algebra and how to use them in Numpy. The following topics will be covered:
- Performing matrix operations (elementwise operations, transpose, multiplication, inverse).
- Properties of matrix multiplication and inverse.
- Representing linear equations in matrix form.
- Solving linear equations using the matrix inverse.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication</a>
            </li>
            <li>
            <a href="#inverses">Task 4: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 5: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 6: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 7: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 8: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 9: Implementing matrix multiplication</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)


---
**Task 1 (easy): Elementwise difference👩‍💻**
1. Calculate $A-B$ in the code cell below.


---


In [5]:
# Write your solution here
R = A-B
print(R)

[[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]



---
**Task 2 (easy): Multiplication properties👩‍💻**
1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).
2. Explain why the results are different.


---


In [9]:
# Write your solution here
ac = np.dot(A,C)
ca = np.dot(C,A)
print(ac)
print(ca)
print("""
They are different because the multiplication of the column and rows changes 
      """)


[[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
[[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]

They are different because the multiplication of the column and rows changes 
      



---
**Task 3 (easy): Elementwise multiplication👩‍💻**
1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators.


---


In [ ]:
# Write your solution here


---
**Task 4 (easy): Inverses👩‍💻**
1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. _Hint: The question relates to the limitations of floating point numbers._


---


In [11]:
# Write your solution here
A_inv = np.linalg.inv(A)
C_inv = np.linalg.inv(C)

print(np.dot(A,A_inv))
print(np.dot(C,C_inv))
print("""
This is due to the float type not being precise. So yes it is the identity matrix, but the precision of the float makes the decimal of the float have a deviation such that it
is not exactly 1
      """)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  1.13686838e-13]
 [-1.33226763e-16  1.00000000e+00 -2.38919995e-14  5.38236122e-14]
 [ 2.47949809e-15 -3.44909286e-14  1.00000000e+00 -2.59052039e-14]
 [-4.12368552e-16  1.10387889e-14 -4.78981933e-14  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.27133892e-14  1.00000000e+00 -1.18882681e-13 -1.96731520e-14]
 [ 5.28219443e-14  2.74965236e-14  1.00000000e+00 -1.43342128e-14]
 [-4.02147451e-15  2.74965236e-14 -1.86591483e-13  1.00000000e+00]]


### Properties

---
**Task 5 (easy): Inverse properties👩‍💻**
Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$


---


In [12]:
# Write your solution here
ED_inv = np.dot(D_inv, E_inv)
DE_inv = np.dot(E_inv, D_inv)

print(ED_inv)
print(DE_inv)

[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
[[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]



---
**Task 6 (easy): The determinant👩‍💻**
1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Based on the results, determine which of the matrices have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-6>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).


---


In [15]:
# Write your solution here
A_det = np.linalg.det(A)
B_det = np.linalg.det(B)
C_det = np.linalg.det(C)

print(A_det)
print(B_det)
print(C_det)

print("""
All determinats indicates that each matrix have an inverse, since the result is not 0. 
If they had a determinant which is 0 then the matrix wouldn't have an inverse
      """)



1.6534391534392702e-07
2.7733391199176e-32
1.0498026371041163e-07

All determinats indicates that each matrix have an inverse, since the result is not 0. 
If they had a determinant which is 0 then the matrix wouldn't have an inverse
      



---
**Task 7 (easy): Transpose👩‍💻**
1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.


**Hint**
The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.



---


In [17]:
# Write your solution here
print((D_inv.T == np.linalg.inv(D.T)).all())

True


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ vector of unknowns, and $b$ is a vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$

---
**Task 8 (medium): Solving linear equation systems👩‍💻**
For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


---


In [ ]:
# Write your solutions here

## Matrix multiplication
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is a new $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.

---
**Task 9 (medium): Implementing matrix multiplication _(optional)_👩‍💻**
Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's built-in functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.

**Hint**
It might be helpful to calculate the correct result by hand first, to make debugging easier.



---


In [ ]:
def matmul(a, b):
    # Implement this function
    ...
    

ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

matmul(ma, mb)

---
